### Get matching passengers for a driver
GET http://localhost:8083/routes/drivers/11/matchingPassengers
Accept: application/json

### Get matching drivers for a passenger
GET http://localhost:8083/routes/passengers/9/matchingDrivers
Accept: application/json

### Get route with passengers (driver with IDs 1,2,3,4,5)
GET http://localhost:8083/routes/drivers/11/withPassengers?passengersIds=1&passengersIds=2&passengersIds=3&passengersIds=4&passengersIds=5
Accept: application/json